
name: Linting

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      name: Use node.js 10
      with:
        node-version: 10.x
    - run: npm install
    - run: npm run lint
